export const POPULAR_GOOGLE_FONT_FAMILIES = [
  "Inter",
  "DM Sans",
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Poppins",
  "Nunito",
  "Raleway",
  "Oswald",
  "Playfair Display",
  "Merriweather",
  "Source Sans 3",
  "Noto Sans",
  "Arial",
  "Comic Sans MS",
  "Arimo",
  "Comic Neue",
  "Caveat",
  "Kalam",
  "Dancing Script",
  "Patrick Hand",
] as const;
